"""Publish tracked HTML and static assets; keep source checkouts out of Pages."""
from html import escape
from html.parser import HTMLParser
from pathlib import Path
import shutil
import subprocess
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "_site"
ASSETS = {".html", ".css", ".js", ".svg", ".png", ".jpg", ".jpeg", ".gif",
          ".webp", ".avif", ".ico", ".woff", ".woff2", ".ttf", ".otf"}


class Title(HTMLParser):
    def __init__(self):
        super().__init__()
        self.active = False
        self.parts = []

    def handle_starttag(self, tag, attrs):
        if tag == "title" and not self.parts:
            self.active = True

    def handle_endtag(self, tag):
        if tag == "title":
            self.active = False

    def handle_data(self, data):
        if self.active:
            self.parts.append(data)


def main():
    tracked = subprocess.check_output(["git", "ls-files", "-z"], cwd=ROOT)
    paths = sorted(Path(p.decode()) for p in tracked.split(b"\0") if p)
    # This directory is generated by this script and ignored by Git.
    if SITE.exists():
        shutil.rmtree(SITE)
    SITE.mkdir()
    pages = []
    for relative in paths:
        if relative.parts[0].startswith(".") or relative.parts[0] == "_site":
            continue
        source = ROOT / relative
        if source.suffix.lower() not in ASSETS or not source.is_file():
            continue
        if source.is_symlink() or ROOT not in source.resolve().parents:
            raise ValueError(f"Static asset must be a regular repository file: {relative}")
        target = SITE / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, target)
        if source.suffix.lower() == ".html":
            title = Title()
            title.feed(source.read_text())
            pages.append((relative.as_posix(), "".join(title.parts).strip() or relative.stem))
    if not pages:
        raise ValueError("No tracked HTML pages found")
    if not (SITE / "index.html").exists():
        items = "\n".join(
            f'<li><a href="{quote(path, safe="/")}">{escape(title)}</a>'
            f'<small>{escape(path)}</small></li>' for path, title in pages
        )
        (SITE / "index.html").write_text("""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Repo Reading — HTML analyses</title>
<style>
body{max-width:880px;margin:64px auto;padding:0 24px;background:#f5f5f5;color:#2d3142;font:16px/1.6 system-ui,sans-serif}
h1{font:400 36px Georgia,serif}a{color:#2e5aa8;text-underline-offset:4px}
ul{list-style:none;padding:0}li{padding:24px 0;border-top:1px solid #bfc0c0}
small{display:block;color:#4f5d75;margin-top:8px}footer{margin-top:48px;color:#4f5d75}
</style></head><body><main><h1>Repo Reading</h1>
<p>Architecture diagrams and source analyses, rendered in your browser.</p>
<ul>""" + items + """</ul>
<footer><a href="https://github.com/intellif-aied/repo-reading">Source repository and walkthroughs</a></footer>
</main></body></html>
""")
    (SITE / ".nojekyll").touch()
    print(f"Built {len(pages)} HTML page(s) in {SITE}")


if __name__ == "__main__":
    main()
